#!/usr/bin/env python3
"""
title: Check for dead links in events.yaml.
summary: |-
  Reads events.yaml, pings each URL, and reports broken links.
  Outputs a markdown report if any errors are found.
"""

import sys
import yaml  # type: ignore
import requests  # type: ignore
from pathlib import Path
from datetime import datetime

# Configuration
PROJECT_ROOT = Path(__file__).resolve().parent.parent
INPUT_FILE = PROJECT_ROOT / "data" / "events.yaml"
REPORT_FILE = PROJECT_ROOT / "broken_links_report.md"

# User Agent to avoid being blocked by some sites
HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
}


def check_link(url: str) -> tuple[bool, str]:
    """
    title: Checks if a URL is reachable.
    parameters:
      url:
        type: str
    returns:
      type: tuple[bool, str]
    """
    try:
        # Try HEAD first as it's faster
        response = requests.head(
            url, headers=HEADERS, timeout=10, allow_redirects=True
        )

        # Some servers block HEAD but allow GET (e.g. 403 or 405 on HEAD)
        if response.status_code in [403, 405]:
            response = requests.get(
                url, headers=HEADERS, timeout=10, allow_redirects=True
            )

        if response.status_code < 400:
            return True, str(response.status_code)
        else:
            return False, f"Status Code: {response.status_code}"
    except requests.exceptions.Timeout:
        return False, "Timeout (10s)"
    except requests.exceptions.ConnectionError:
        return False, "Connection Error"
    except Exception as e:
        return False, f"Error: {str(e)}"


def main() -> None:
    """
    title: Main function to check all event links and generate a report.
    """
    if not INPUT_FILE.exists():
        print(f"Error: Input file not found: {INPUT_FILE}")
        sys.exit(1)

    print(f"Reading events from: {INPUT_FILE}")
    with open(INPUT_FILE, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f)

    events = data.get("events", [])
    if not events:
        print("No events found to check.")
        return

    broken_links = []
    print(f"Checking {len(events)} events...")

    for event in events:
        eid = event.get("id", "Unknown ID")
        title = event.get("title", "Unknown Title")
        url = event.get("url")

        if not url:
            continue

        print(f"  [{eid}] Checking: {url} ... ", end="", flush=True)
        is_ok, result = check_link(url)

        if is_ok:
            print(f"✅ ({result})")
        else:
            print(f"❌ ({result})")
            broken_links.append(
                {"id": eid, "title": title, "url": url, "reason": result}
            )

    if broken_links:
        print(f"\nFound {len(broken_links)} broken links.")

        # Generate Markdown Report for GitHub Issue
        report_content = [
            "# 🚨 Broken Event Links Detected",
            f"\nChecked on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            "\nThe following events have unreachable registration or info links. PLEASE UPDATE THEM in `data/events.yaml`.",
            "\n| Event ID | Title | Broken URL | Reason |",
            "| :--- | :--- | :--- | :--- |",
        ]

        for item in broken_links:
            report_content.append(
                f"| `{item['id']}` | {item['title']} | [{item['url']}]({item['url']}) | {item['reason']} |"
            )

        report_content.append(
            "\n\n---\n*This issue was automatically generated by the Weekly Link Guardian.*"
        )

        with open(REPORT_FILE, "w", encoding="utf-8") as f:
            f.write("\n".join(report_content))

        print(f"Report saved to: {REPORT_FILE}")
        sys.exit(1)  # Signal failure
    else:
        print("\nAll links are healthy! 🎉")
        # Ensure report file doesn't exist if all is clear
        if REPORT_FILE.exists():
            REPORT_FILE.unlink()
        sys.exit(0)


if __name__ == "__main__":
    main()
